//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int ID { get; set; }
        public string ADMINEMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string AUTHORITY { get; set; }
    }
}
