//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNOUNCEMENT
    {
        public byte ID { get; set; }
        public string AN_CATEGORY { get; set; }
        public string TEXT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
