//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNISHMENT
    {
        public int ID { get; set; }
        public Nullable<int> USERINFO { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public Nullable<int> LOANS { get; set; }
    
        public virtual LOANS LOANS1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
