//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.LOANS = new HashSet<LOANS>();
            this.PUNISHMENT = new HashSet<PUNISHMENT>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Name is required")]
        [StringLength(20,ErrorMessage ="Max 20 Characters")]
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public string USERNAME { get; set; }
        [StringLength(10, ErrorMessage = "Max 10 Characters")]
        public string PASSWORD { get; set; }
        public string IMAGE { get; set; }
        public string PHONE { get; set; }
        public string SCHOOLNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOANS> LOANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNISHMENT> PUNISHMENT { get; set; }
    }
}
